# Generated by Django 4.1.7 on 2023-03-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('Client_sore', models.IntegerField(default=0)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
