# Generated by Django 4.1.7 on 2023-03-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_project_client_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
